name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.54.2/golangci-lint-1.54.2-linux-amd64.tar.gz -o golangci-lint.tar.gz
          tar -xvzf golangci-lint.tar.gz
          mv golangci-lint-1.54.2-linux-amd64/golangci-lint /usr/local/bin/

      - name: Run linter
        run: golangci-lint run --config=.golangci.yml
      - name: Run Tests
        run: make test
      - name: Build image
        run: make build
      - name: run image
        run: make run
