name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: check version
        run: go version
      - name: Install Dependencies
        run: go mod tidy
      - name: Run Linter
        run: make lint
      - name: Run Tests
        run: make test
      - name: Build image
        run: make build
      - name: run image
        run: make run
