name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Install GolangCI-Lint
        run: |
          mkdir -p ${HOME}/bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ${HOME}/bin v1.54.2

      - name: Add Go Bin to PATH
        run: echo "${HOME}/go/bin:/usr/local/bin" >> $GITHUB_PATH

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.2
          args: --timeout=10m --config=.golangci.yml --issues-exit-code=0
      - name: Run Tests
        run: make test
      - name: Build image
        run: make build
      - name: run image
        run: make run
