name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Debug environment
        run: |
          go version
          go env
          ls -la
      - name: Install dependencies
        run: go mod tidy

      - name: Run linter
        run: golangci-lint run --config=.golangci.yml
      - name: Run Tests
        run: make test
      - name: Build image
        run: make build
      - name: run image
        run: make run
